# Generated by Django 5.1.4 on 2026-01-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_email_6b9219_idx',
            old_name='audit_audit_email_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_event_07f862_idx',
            old_name='audit_audit_event_created_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
